
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ISHIKA MITTAL
 */
public class Dialog2 extends javax.swing.JDialog {

    /**
     * Creates new form Dialog2
     */
    public Dialog2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(410,210);
        setTitle("Replace");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        b2 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        Matchcase = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Find and Replace");
        setResizable(false);
        getContentPane().setLayout(null);

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(90, 80, 190, 30);

        jLabel1.setText("Replace with :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 80, 80, 30);

        b2.setText("Find Next");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2);
        b2.setBounds(290, 40, 90, 20);

        b1.setText("Replace All");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(290, 80, 90, 20);

        Matchcase.setText("Match case");
        Matchcase.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MatchcaseItemStateChanged(evt);
            }
        });
        getContentPane().add(Matchcase);
        Matchcase.setBounds(10, 130, 90, 21);

        jLabel3.setText("Find what :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 40, 80, 30);

        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        getContentPane().add(t2);
        t2.setBounds(90, 40, 190, 30);

        b3.setText("Cancel");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3);
        b3.setBounds(290, 100, 90, 20);

        b4.setText("Replace");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        getContentPane().add(b4);
        b4.setBounds(290, 60, 90, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        //FIND NEXT
        FindNext();
    }//GEN-LAST:event_b2ActionPerformed
   public void FindNext()
        {
            String ta = frame1.t1.getText();
             String find = t2.getText();
            int caretpos = frame1.t1.getCaretPosition();
            /*Down Selected*/
                String sub = ta.substring(caretpos,ta.length());
                if(caretpos==ta.length())
                {
                    JOptionPane.showMessageDialog(this,"Cannot Find "+find);
                }
                else
                {
                    if(Matchcase.isSelected())
                    {
                        if(!sub.contains(find))
                        {
                                JOptionPane.showMessageDialog(this,"Cannot Find "+find);
                        }
                        else
                        {
                            int index = ta.indexOf(find,caretpos);
                            frame1.t1.select(index, index+find.length());
                            if(index==ta.lastIndexOf(find, ta.length()))
                            {
                               // t1.setText("AAGYA");
                            //    frame1.t1.s
                            }
                         }
                    }
                    /*Matchcase Not Selected*/
                    else
                    {
                        String FIND = find.toUpperCase();
                        String TA = ta.toUpperCase();
                        String SUB = sub.toUpperCase();
                        if(!SUB.contains(FIND))
                        {
                           JOptionPane.showMessageDialog(this,"Cannot Find "+find);
                        }
                        else
                        {
                            int index = TA.indexOf(FIND,caretpos);
                            frame1.t1.select(index, index+FIND.length());
                        }
                    }
                }
            }
    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        //REPLACE
        String rep = t1.getText();
        String tf = t2.getText();
        String ta = frame1.t1.getText();
        int n = frame1.t1.getCaretPosition();
        if(n==ta.length())
        {
            JOptionPane.showMessageDialog(this,"Cannot find "+tf);
        }
        else
        {
            String prevsub = ta.substring(0,n);
            String sub = ta.substring(n,ta.length());
            if(!sub.contains(tf))
            {
                JOptionPane.showMessageDialog(this,"Cannot find "+tf);
            }
            else
            {
                    int index = sub.indexOf(tf,n);
                    frame1.t1.setText(prevsub + sub.replaceFirst(tf, rep));
                    frame1.t1.setCaretPosition(index+tf.length());
            }
        }
    }//GEN-LAST:event_b4ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        //CANCEL
        this.setVisible(false);
    }//GEN-LAST:event_b3ActionPerformed

    private void MatchcaseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MatchcaseItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_MatchcaseItemStateChanged

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        //REPLACE ALL
        String ta = frame1.t1.getText();
        String tf = t2.getText();
        String rep = t1.getText();
        frame1.t1.setText(ta.replaceAll(tf, rep ));
    }//GEN-LAST:event_b1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dialog2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dialog2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dialog2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dialog2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dialog2 dialog = new Dialog2(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Matchcase;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField t1;
    private static javax.swing.JTextField t2;
    // End of variables declaration//GEN-END:variables
}
