
import javax.swing.JOptionPane;





/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ISHIKA MITTAL
 */
public class Dialog1 extends javax.swing.JDialog {

    /**
     * Creates new form Dialog1
     */
    static String find;
    public Dialog1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Find");
       setSize(410,190);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        t1 = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        Matchcase = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(200, 250, 400, 180));
        setResizable(false);
        getContentPane().setLayout(null);

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(70, 40, 210, 30);

        b1.setText("Cancel");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(290, 70, 90, 30);

        b2.setText("Find Next");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2);
        b2.setBounds(290, 40, 90, 30);

        jLabel1.setText("Find what :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 40, 70, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(170, 90, 90, 0);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Direction");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 80, 70, 30);

        buttonGroup1.add(r1);
        r1.setSelected(true);
        r1.setText("Up");
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });
        getContentPane().add(r1);
        r1.setBounds(170, 110, 40, 21);

        buttonGroup1.add(r2);
        r2.setText("Down");
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });
        getContentPane().add(r2);
        r2.setBounds(220, 110, 53, 21);

        Matchcase.setText("Match case");
        Matchcase.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MatchcaseItemStateChanged(evt);
            }
        });
        getContentPane().add(Matchcase);
        Matchcase.setBounds(20, 100, 90, 21);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        //FIND NEXT
        String ta = frame1.t1.getText();
        find = t1.getText();
        int caretpos = frame1.t1.getCaretPosition();
        /*Down Selected*/
        if(r2.isSelected())
        {
            String sub = ta.substring(caretpos,ta.length());
            if(caretpos==ta.length())
            {
                JOptionPane.showMessageDialog(this,"Cannot Find "+find);
            }
            else
            {
                if(Matchcase.isSelected())
                {
                    if(!sub.contains(find))
                    {
                            JOptionPane.showMessageDialog(this,"Cannot Find "+find);
                    }
                    else
                    {
                        int index = ta.indexOf(find,caretpos);
                        frame1.t1.select(index, index+find.length());
                        if(index==ta.lastIndexOf(find, ta.length()))
                        {
                           // t1.setText("AAGYA");
                        //    frame1.t1.s
                        }
                     }
                }
                /*Matchcase Not Selected*/
                else
                {
                    String FIND = find.toUpperCase();
                    String TA = ta.toUpperCase();
                    String SUB = sub.toUpperCase();
                    if(!SUB.contains(FIND))
                    {
                       JOptionPane.showMessageDialog(this,"Cannot Find "+find);
                    }
                    else
                    {
                        int index = TA.indexOf(FIND,caretpos);
                        frame1.t1.select(index, index+FIND.length());
                    }
                }
            }
        }
        /*Up Selected*/
        else
        {
            String sub = ta.substring(0,caretpos);
            if(caretpos<0 || caretpos>ta.length())
            {
                JOptionPane.showMessageDialog(this,"Cannot Find "+find);
            }
            else
            {
                if(Matchcase.isSelected())
                {
                    if(!sub.contains(find))
                    {
                        JOptionPane.showMessageDialog(this,"Cannot Find "+find);
                    }
                    else
                    {
                        int index = sub.lastIndexOf(find,caretpos);
                        frame1.t1.setCaretPosition(index+find.length());
                        frame1.t1.moveCaretPosition(index);
                        //t1.setText(frame1.t1.getCaretPosition()+"");
                    }
                }
                /*Matchcase Not Selected*/
                else
                {
                    String  FIND = find.toUpperCase();
                    String TA = ta.toUpperCase();
                    String SUB = sub.toUpperCase();
                    if(!SUB.contains(FIND))
                    {
                        JOptionPane.showMessageDialog(this,"Cannot Find "+find);
                    }
                    else
                    {
                        int index = SUB.lastIndexOf(FIND,caretpos);
                        frame1.t1.setCaretPosition(index+FIND.length());
                        frame1.t1.moveCaretPosition(index);
                    }
                }
            }
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_r2ActionPerformed

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        // TODO add your handling code here:
        //UP
    }//GEN-LAST:event_r1ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        //CANCEL
        this.setVisible(false);
    }//GEN-LAST:event_b1ActionPerformed

    private void MatchcaseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MatchcaseItemStateChanged
        // TODO add your handling code here:
        //MatchCase
    }//GEN-LAST:event_MatchcaseItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dialog1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dialog1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dialog1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dialog1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dialog1 dialog = new Dialog1(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Matchcase;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    public static javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
